### ISSUE TITLE
Error: Unhashable Type

### ISSUE THREAD

**Issue by edlgm** [diegogarciahuerta/tk-substancepainter#17]
After merging all the ymls and trying to run the tank cache_apps command I get the following error:

ERROR: A general error was reported: unhashable type
Traceback (most recent call last):
  File "C:\Volumes\project\6_ShotgunConfig\install\core\scripts\tank_cmd.py", line 1860, in <module>
    pipeline_config_root, ctx_list, cmd_name, using_cwd, cmd_args
  File "C:\Volumes\project\6_ShotgunConfig\install\core\scripts\tank_cmd.py", line 1510, in run_engine_cmd
    return run_action(logger, tk, ctx, command, args)
  File "C:\Volumes\project\6_ShotgunConfig\install\core\python\tank\commands\tank_command.py", line 563, in run_action
    return found_action.run_interactive(log, args)
  File "C:\Volumes\project\6_ShotgunConfig\install\core\python\tank\commands\cache_apps.py", line 63, in run_interactive
    return self._run(log)
  File "C:\Volumes\project\6_ShotgunConfig\install\core\python\tank\commands\cache_apps.py", line 81, in _run
    env = self.tk.pipeline_configuration.get_environment(env_name)
  File "C:\Volumes\project\6_ShotgunConfig\install\core\python\tank\pipelineconfig.py", line 1149, in get_environment
    env_obj = EnvClass(env_file, self, context)
  File "C:\Volumes\project\6_ShotgunConfig\install\core\python\tank\platform\environment.py", line 762, in __init__
    super(InstalledEnvironment, self).__init__(env_path, context)
  File "C:\Volumes\project\6_ShotgunConfig\install\core\python\tank\platform\environment.py", line 63, in __init__
    self._refresh()
  File "C:\Volumes\project\6_ShotgunConfig\install\core\python\tank\platform\environment.py", line 77, in _refresh
    self._env_path, data, self.__context
  File "C:\Volumes\project\6_ShotgunConfig\install\core\python\tank\platform\environment_includes.py", line 186, in process_includes
    data, _ = _process_includes_r(file_name, data, context)
  File "C:\Volumes\project\6_ShotgunConfig\install\core\python\tank\platform\environment_includes.py", line 210, in _process_includes_r
    include_files = _resolve_includes(file_name, data, context)
  File "C:\Volumes\project\6_ShotgunConfig\install\core\python\tank\platform\environment_includes.py", line 118, in _resolve_includes
    path = resolve_include(file_name, include)
  File "C:\Volumes\project\6_ShotgunConfig\install\core\python\tank\util\includes.py", line 72, in resolve_include
    path = os.path.expanduser(os.path.expandvars(include))
  File "C:\Program Files\Shotgun\Python\lib\ntpath.py", line 289, in expanduser
    if path[:1] != '~':
TypeError: unhashable type

Do you know what the issue might be?

**Comment by MoisMoshev** [comment]
It could be a wrong include in the yml of a non-existent yml fie.
